import type { ServerNotificationEnvelope } from "@codex-everywhere/codex-app-server-schema";
import { Ajv, type ValidateFunction } from "ajv";

import type { CodexNotification } from "../../runtime/codex-app-server-client.js";
import serverNotificationSchema from "./generated/server-notification.schema.json" with { type: "json" };

let validator: ValidateFunction | undefined;
const GENERIC_ONLY_NOTIFICATION_METHODS = new Set([
  "modelProvider/authRecoveryStarted",
  "modelProvider/authRecoveryCompleted",
]);

/** Validates against the JSON Schema generated by the pinned Codex CLI. */
export function isKnownCodexNotification(
  notification: CodexNotification,
): notification is ServerNotificationEnvelope {
  // These notifications are schema-known in the pinned CLI, but CE has no
  // structured presentation for them yet. Keep them visible through the
  // forward-compatible generic timeline instead of silently discarding them.
  if (GENERIC_ONLY_NOTIFICATION_METHODS.has(notification.method)) return false;
  const validate = (validator ??= new Ajv({
    allErrors: false,
    strict: false,
    validateFormats: false,
  }).compile(serverNotificationSchema));
  return validate(notification);
}
