import type { ServerNotificationEnvelope } from "@codex-everywhere/codex-app-server-schema";
import { Ajv, type ValidateFunction } from "ajv";

import type { CodexNotification } from "../../runtime/codex-app-server-client.js";
import serverNotificationSchema from "./generated/server-notification.schema.json" with { type: "json" };

let validator: ValidateFunction | undefined;

/** Validates against the JSON Schema generated by the pinned Codex CLI. */
export function isKnownCodexNotification(
  notification: CodexNotification,
): notification is ServerNotificationEnvelope {
  const validate = (validator ??= new Ajv({
    allErrors: false,
    strict: false,
    validateFormats: false,
  }).compile(serverNotificationSchema));
  return validate(notification);
}
